services:
  mysql:
    image: mysql:8.4
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3307:3306
  flyway-mysql-default:
    image: flyway/flyway
    command:
    - -url=jdbc:mysql://mysql:3306?allowPublicKeyRetrieval=true
    - -schemas=default
    - -user=root
    - -password=password
    - -connectRetries=60
    - -cleanOnValidationError=true
    - migrate
    volumes:
    - ./slick-codegen-patch/src/test/resources/flyway/mysql-default:/flyway/sql
    depends_on:
    - mysql
